(function(){
'use strict';
const C=window.PriorityCashCore;
let state=C.loadState();
let active='summary';
let saveTimer=null;
const view=document.getElementById('view'),saveBtn=document.getElementById('save');
const CATEGORIES=['','A','B','C','D','Коммуналка сверх','Еда','Транспорт','Кофе','Аптека','Другое'];
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function money(n){return C.formatMoney(n)}
function info(p){return state.settings.priorities[p]||C.DEFAULT_PRIORITIES[p]}
function theme(){document.documentElement.dataset.theme=state.settings.theme||'auto'}
function saving(){saveBtn.className='save saving';saveBtn.innerHTML='<span></span>'}
function saved(){saveBtn.className='save saved';saveBtn.innerHTML='<span>✓</span>'}
function saveSoon(){clearTimeout(saveTimer);saving();saveTimer=setTimeout(()=>{state=C.ensureState(state);C.saveState(state);saved();theme()},250)}
function saveNow(){clearTimeout(saveTimer);state=C.ensureState(state);C.saveState(state);saved();theme()}
function render(){theme();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===active));if(active==='summary')summary();if(active==='months')months();if(active==='budget')budget();if(active==='settings')settings();if(active==='support')support()}
function priorityCard(p,s){const target=s.totals.target[p]||0,spent=s.saved[p]||0,left=Math.max(0,target-spent),percent=target?Math.min(100,spent/target*100):100,i=info(p);return `<section class="card"><div class="head"><div class="ptitle"><span class="badge ${p}">${p}</span><div><h3>${esc(i.title)}</h3><p style="margin:3px 0 0">${esc(i.description)}</p></div></div><span class="chip">${s.closedAt[p]?C.formatDate(s.closedAt[p]):'Не закрыто'}</span></div><div class="bar"><div class="fill" style="width:${percent}%"></div></div><div class="money"><div><small>В цели было</small><b>${money(target)}</b></div><div><small>Потрачено в цель</small><b>${money(spent)}</b></div><div><small>Осталось для погашения цели</small><b>${money(left)}</b></div></div></section>`}
function summary(){const s=C.computePlan(state),next=['A','B','C','D'].find(p=>s.rem[p]>0)||'все закрыто',g=esc(state.settings.goalName);view.innerHTML=`<section class="card hero"><h2>${state.settings.userName?esc(state.settings.userName)+', ':''}контролируй свои финансы</h2><p>Остаток с месяца после фактических трат и “${g}” идет в первый незакрытый приоритет.</p><div class="grid"><div class="mini"><small>Следующий приоритет</small><strong>${next}</strong></div><div class="mini"><small>${g} накоплено</small><strong>${money(s.goalTotal)}</strong></div></div></section>${['A','B','C','D'].map(p=>priorityCard(p,s)).join('')}`}
function num(label,iso,key,val){return `<div class="field"><label>${label}</label><input type="number" inputmode="numeric" min="0" step="100" value="${Math.round(val)}" data-month="${iso}" data-key="${key}"></div>`}
function catSelect(iso,day,val){return `<select class="catSelect" data-day-category="${iso}" data-day="${day}">${CATEGORIES.map(c=>`<option value="${esc(c)}" ${c===val?'selected':''}>${c?esc(c):'Кат.'}</option>`).join('')}</select>`}
function calendar(r){const d=C.dateFromISO(r.iso),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1).getDay()||7,today=new Date(),cur=today.getFullYear()===y&&today.getMonth()===m,tday=cur?today.getDate():0;let out=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="calh">${x}</div>`).join('');for(let i=1;i<first;i++)out+='<div></div>';for(let day=1;day<=days;day++){const daily=r.daily[String(day)]||{};out+=`<div class="day ${cur&&day===tday?'today':''} ${daily.amount?'extra':''}"><div class="num">${day}</div><input class="extraInput" type="number" inputmode="numeric" min="0" step="100" placeholder="+трата" value="${daily.amount?Math.round(daily.amount):''}" data-day-extra="${r.iso}" data-day="${day}">${catSelect(r.iso,day,daily.category||'')}${daily.amount?`<div class="extraText">+${Math.round(daily.amount)} ₽</div>`:''}</div>`}return out}
function monthCard(r){const g=esc(state.settings.goalName);return `<section class="card" data-month-card="${r.iso}"><div class="head"><div><h3>${r.label}</h3><p>Куда ушло: <b data-out="goesTo">${r.goesTo}</b> · <span data-out="status">${esc(r.status)}</span></p></div><span class="pill free" data-out="free">${money(r.freeMoney)}</span></div><div class="form">${num('Доход',r.iso,'income',r.income)}${num('Сколько планируется потратить',r.iso,'expenses',r.expenses)}${num(g,r.iso,'goal',r.goalInput)}</div><div class="mgrid"><div><small>Сколько потрачено</small><b data-out="daily">${money(r.dailyExtra)}</b></div><div><small>Остаток с месяца</small><b data-out="free2">${money(r.freeMoney)}</b></div><div><small>Остаток A</small><b data-out="remA">${money(r.rem.A)}</b></div><div><small>Остаток B</small><b data-out="remB">${money(r.rem.B)}</b></div></div><div class="pline"><span data-out="payA">A ${money(r.pay.A)}</span><span data-out="payB">B ${money(r.pay.B)}</span><span data-out="payC">C ${money(r.pay.C)}</span><span data-out="payD">D ${money(r.pay.D)}</span></div><details><summary class="section">Календарь дополнительных трат</summary><div class="calendar" data-calendar="${r.iso}">${calendar(r)}</div></details><div class="field"><label>Комментарий</label><textarea data-month="${r.iso}" data-key="note">${esc(r.note)}</textarea></div></section>`}
function months(){const s=C.computePlan(state);view.innerHTML=`<div class="toolbar"><button class="btn primary" data-action="recalc">Полный пересчет</button><button class="btn" data-action="remove-months">- 12 месяцев</button><button class="btn" data-action="add-months">+ 12 месяцев</button></div><section class="card"><p>Фактические расходы собираются из ежедневных трат в календаре. При вводе суммы клавиатура не должна пропадать.</p></section>${s.rows.map(monthCard).join('')}`}
function updateVisible(skipCalendar=true){const s=C.computePlan(state);for(const r of s.rows){const c=view.querySelector(`[data-month-card="${r.iso}"]`);if(!c)continue;const set=(k,v)=>{const e=c.querySelector(`[data-out="${k}"]`);if(e)e.textContent=v};set('goesTo',r.goesTo);set('status',r.status);set('free',money(r.freeMoney));set('free2',money(r.freeMoney));set('daily',money(r.dailyExtra));set('remA',money(r.rem.A));set('remB',money(r.rem.B));set('payA','A '+money(r.pay.A));set('payB','B '+money(r.pay.B));set('payC','C '+money(r.pay.C));set('payD','D '+money(r.pay.D));if(!skipCalendar){const cal=c.querySelector(`[data-calendar="${r.iso}"]`);if(cal)cal.innerHTML=calendar(r)}}}
function budget(){const s=C.computePlan(state);view.innerHTML=`<section class="card"><h3>Бюджет</h3><p>Добавляй новые цели и статьи. Они сразу участвуют в расчете.</p></section><section class="card"><h3>Добавить строку</h3><div class="addBudget"><div class="field"><label>Приоритет</label><select id="newP"><option>A</option><option>B</option><option>C</option><option>D</option></select></div><div class="field"><label>Название</label><input id="newN"></div><div class="field"><label>Сумма</label><input id="newA" type="number" min="0" step="100"></div></div><div class="toolbar"><button class="btn primary" data-action="add-budget">Добавить</button></div></section>${state.budget.map((it,i)=>`<section class="card budgetRow"><span class="badge ${it.priority}">${it.priority}</span><input value="${esc(it.name)}" data-budget-name="${i}"><input type="number" min="0" step="100" value="${Math.round(C.toNumber(it.amount))}" data-budget-amount="${i}"><button class="btn danger" data-delete-budget="${i}">×</button></section>`).join('')}<section class="card"><h3>Итого с буфером</h3><div class="money"><div><small>A</small><b>${money(s.totals.target.A)}</b></div><div><small>B</small><b>${money(s.totals.target.B)}</b></div><div><small>C</small><b>${money(s.totals.target.C)}</b></div></div></section>`}
function settings(){const st=state.settings;view.innerHTML=`<section class="card"><h3>Настройки</h3><p>Настройки сохраняются только на устройстве пользователя.</p></section><section class="card"><div class="form"><div class="field"><label>Ник пользователя</label><input value="${esc(st.userName)}" data-setting-text="userName"></div><div class="field"><label>Тема</label><select data-setting-text="theme"><option value="auto" ${st.theme==='auto'?'selected':''}>Как в телефоне</option><option value="light" ${st.theme==='light'?'selected':''}>Светлая</option><option value="dark" ${st.theme==='dark'?'selected':''}>Тёмная</option></select></div><div class="field"><label>Название отдельной цели</label><input value="${esc(st.goalName)}" data-setting-text="goalName"></div></div></section><section class="card"><h3>Названия приоритетов</h3>${['A','B','C','D'].map(p=>`<div class="field"><label>${p}: название</label><input value="${esc(st.priorities[p].title)}" data-priority-title="${p}"></div><div class="field"><label>${p}: пояснение</label><textarea data-priority-desc="${p}">${esc(st.priorities[p].description)}</textarea></div>`).join('')}</section><section class="card">${settingFields().map(([k,l,t,step])=>`<div class="field"><label>${l}</label><input type="${t}" step="${step||1}" value="${esc(st[k])}" data-setting="${k}"></div>`).join('')}</section><section class="card"><details><summary>Данные, экспорт и импорт</summary>${dataTools()}</details></section>`}
function settingFields(){return[['startDate','Дата старта','date'],['deadlineA','Дедлайн A','date'],['deadlineB','Дедлайн B','date'],['deadlineC','Дедлайн C','date'],['defaultIncome','Доход по умолчанию','number'],['defaultExpenses','План трат по умолчанию','number'],['maxGoal','Лимит отдельной цели','number'],['defaultGoal','Отдельная цель по умолчанию','number'],['startCash','Стартовый остаток','number'],['startGoal','Уже накоплено по отдельной цели','number'],['reserve','Резерв','number'],['bufferAB','Буфер A/B','number','0.01'],['bufferC','Буфер C','number','0.01'],['bufferD','Буфер D','number','0.01'],['months','Месяцев в плане','number']]}
function dataTools(){return `<p>Скачай JSON перед крупными изменениями или переносом на другое устройство.</p><div class="toolbar"><button class="btn primary" data-action="export-json">Скачать JSON</button><label class="btn">Импорт JSON<input type="file" hidden accept="application/json" data-action="import-json"></label><button class="btn" data-action="export-csv">Скачать CSV</button><button class="btn danger" data-action="reset">Сбросить</button></div><div class="dataBox">${esc(JSON.stringify(C.ensureState(state),null,2))}</div>`}
function support(){view.innerHTML=`<section class="card hero"><h2>Поддержка и инструкция</h2><p>Краткая инструкция по работе с приложением.</p></section><section class="card"><ol class="support"><li><b>Сводка:</b> показывает, сколько было в цели, сколько потрачено в цель и сколько осталось для погашения.</li><li><b>Месяцы:</b> внеси доход и план трат. Фактические расходы собираются из ежедневных трат в календаре.</li><li><b>Календарь:</b> раскрой месяц и добавляй дополнительные траты по дням. Категория не обязательна.</li><li><b>Бюджет:</b> добавляй новые цели, статьи и суммы.</li><li><b>Настройки:</b> меняй ник, тему, названия приоритетов и название отдельной цели.</li><li><b>Данные:</b> находятся внизу настроек. Там экспорт и импорт JSON.</li></ol></section><section class="card"><h3>Поддержка</h3><p>По всем вопросам сюда: <b>@COM4KA</b></p></section>`}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(){const s=C.computePlan(state),h=['month','income','planned_spend','spent_from_days','goal','free','goes_to','A','B','C','D'];const rows=s.rows.map(r=>[r.label,r.income,r.expenses,r.dailyExtra,r.goalFact,r.freeMoney,r.goesTo,r.pay.A,r.pay.B,r.pay.C,r.pay.D]);return[h,...rows].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n')}
document.querySelector('nav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;active=b.dataset.tab;render()});
view.addEventListener('input',e=>{const el=e.target;if(el.dataset.dayExtra){const iso=el.dataset.dayExtra,day=el.dataset.day;state.months[iso]=state.months[iso]||{};state.months[iso].daily=state.months[iso].daily||{};const old=state.months[iso].daily[day]||{};const amount=C.toNumber(el.value);if(amount>0)state.months[iso].daily[day]=Object.assign({},old,{amount});else delete state.months[iso].daily[day];saveSoon();updateVisible(true);return}if(el.dataset.month){const iso=el.dataset.month,key=el.dataset.key;state.months[iso]=state.months[iso]||{};state.months[iso][key]=key==='note'?el.value:C.toNumber(el.value);saveSoon();updateVisible(true);return}if(el.dataset.setting){state.settings[el.dataset.setting]=el.type==='date'?el.value:C.toNumber(el.value);saveSoon();return}if(el.dataset.settingText){state.settings[el.dataset.settingText]=el.value;saveSoon();theme();return}if(el.dataset.priorityTitle){state.settings.priorities[el.dataset.priorityTitle].title=el.value;saveSoon();return}if(el.dataset.priorityDesc){state.settings.priorities[el.dataset.priorityDesc].description=el.value;saveSoon();return}if(el.dataset.budgetAmount){state.budget[Number(el.dataset.budgetAmount)].amount=C.toNumber(el.value);saveSoon();return}if(el.dataset.budgetName){state.budget[Number(el.dataset.budgetName)].name=el.value;saveSoon();return}});
view.addEventListener('change',e=>{const el=e.target;if(el.dataset.dayCategory){const iso=el.dataset.dayCategory,day=el.dataset.day;state.months[iso]=state.months[iso]||{};state.months[iso].daily=state.months[iso].daily||{};const old=state.months[iso].daily[day]||{};if(el.value||old.amount)state.months[iso].daily[day]=Object.assign({},old,{category:el.value});saveNow();return}if(el.dataset.action==='import-json'){const f=el.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=C.ensureState(JSON.parse(r.result));saveNow();render();alert('Импорт готов')}catch(_){alert('Файл не похож на JSON приложения')}};r.readAsText(f);return}if(el.matches('input,textarea,select'))saveNow()});
view.addEventListener('click',e=>{const del=e.target.closest('[data-delete-budget]');if(del){if(confirm('Удалить строку бюджета?')){state.budget.splice(Number(del.dataset.deleteBudget),1);saveNow();render()}return}const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='recalc'){saveNow();render()}if(a==='add-months'){state.settings.months=C.toNumber(state.settings.months,48)+12;saveNow();render()}if(a==='remove-months'){state.settings.months=Math.max(12,C.toNumber(state.settings.months,48)-12);saveNow();render()}if(a==='add-budget'){const name=document.getElementById('newN').value.trim(),amount=C.toNumber(document.getElementById('newA').value),priority=document.getElementById('newP').value;if(!name){alert('Введи название');return}state.budget.push({priority,name,amount});saveNow();render()}if(a==='export-json')download('prioritycash-data.json',JSON.stringify(C.ensureState(state),null,2),'application/json');if(a==='export-csv')download('prioritycash-months.csv',csv(),'text/csv;charset=utf-8');if(a==='reset'&&confirm('Сбросить данные только на этом устройстве?')){state=C.clone(C.DEFAULT_STATE);saveNow();render()}});
function setupAutoUpdate(){if(!('serviceWorker'in navigator)||location.protocol==='file:')return;let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').then(reg=>{if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});reg.addEventListener('updatefound',()=>{const w=reg.installing;if(w)w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)w.postMessage({type:'SKIP_WAITING'})})});setInterval(()=>reg.update().catch(()=>{}),30*60*1000)}).catch(()=>{}))}setupAutoUpdate();theme();render();})();
