(function(){
'use strict';
const C=window.PriorityCashCore;
let state=C.loadState();
let activeTab='dashboard';
const view=document.getElementById('view');
const saveIndicator=document.getElementById('saveIndicator');
let saveTimer=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
function money(n){return C.formatMoney(n);} function pInfo(p){return state.settings.priorities[p]||C.DEFAULT_PRIORITIES[p];}
function saveSoon(){ clearTimeout(saveTimer); saveIndicator.textContent='Сохраняю...'; saveIndicator.classList.add('dirty'); saveTimer=setTimeout(()=>{state=C.ensureState(state); C.saveState(state); saveIndicator.textContent='Сохранено'; saveIndicator.classList.remove('dirty');},250); }
function saveNow(){ state=C.ensureState(state); C.saveState(state); saveIndicator.textContent='Сохранено'; saveIndicator.classList.remove('dirty'); }
function render(){ document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===activeTab)); if(activeTab==='dashboard')dashboard(); if(activeTab==='plan')plan(); if(activeTab==='budget')budget(); if(activeTab==='settings')settings(); if(activeTab==='data')dataView(); }
function cardPriority(p,sum){const info=pInfo(p),target=sum.totals.target[p]||0,saved=sum.saved[p]||0,left=Math.max(0,target-saved),pct=target?Math.min(100,saved/target*100):100,dt=sum.closedAt[p]?C.formatDate(sum.closedAt[p]):'Не закрыто';return `<section class="card priority-card"><div class="priority-head"><div class="priority-title"><span class="badge ${p}">${p}</span><div><h3>${esc(info.title)}</h3><p style="margin:3px 0 0">${esc(info.description)}</p></div></div><span class="date-chip">${dt}</span></div><div class="progress"><div class="progress-fill" style="width:${pct}%"></div></div><div class="money-grid"><div><small>Цель</small><b>${money(target)}</b></div><div><small>Накоплено</small><b>${money(saved)}</b></div><div><small>Осталось</small><b>${money(left)}</b></div></div></section>`;}
function dashboard(){const sum=C.computePlan(state); const next=['A','B','C','D'].find(p=>sum.rem[p]>0)||'все закрыто'; view.innerHTML=`<section class="card hero"><h2>Финансовый водопад</h2><p>Остаток после расходов и комнаты автоматически уходит в первый незакрытый приоритет.</p><div class="kpi-grid"><div class="kpi dark"><small>Следующий приоритет</small><strong>${esc(next)}</strong></div><div class="kpi dark"><small>Комната накоплено</small><strong>${money(sum.roomTotal)}</strong></div></div></section><section class="help-box"><b>Пример:</b> доход 250 000 - расходы 140 000 - комната 0 = 110 000 ₽ в приоритет. Если комната 35 000 ₽, в приоритет уйдет 75 000 ₽.</section><p class="section-title">Приоритеты</p>${['A','B','C','D'].map(p=>cardPriority(p,sum)).join('')}`;}
function monthCard(r){const cls=r.status==='OK'||r.status.includes('закрыт')?'ok':'warning';return `<section class="card month-card" id="m-${r.iso}"><div class="month-top"><div><div class="month-title">${r.index}. ${r.label}</div><div class="month-sub">Куда ушло: <b>${r.goesTo}</b> · ${esc(r.status)}</div></div><span class="pill ${cls}">${money(r.toPriority)}</span></div><div class="form-grid"><div class="field"><label>Доход</label><input inputmode="numeric" type="number" min="0" step="100" value="${Math.round(r.income)}" data-month="${r.iso}" data-key="income"></div><div class="field"><label>Расходы</label><input inputmode="numeric" type="number" min="0" step="100" value="${Math.round(r.expenses)}" data-month="${r.iso}" data-key="expenses"></div><div class="field"><label>Комната</label><input inputmode="numeric" type="number" min="0" step="100" value="${Math.round(r.roomInput)}" data-month="${r.iso}" data-key="room"></div></div><div class="month-money"><div><small>В приоритет</small><b data-live="to-${r.iso}">${money(r.toPriority)}</b></div><div><small>Комната факт</small><b>${money(r.roomFact)}</b></div><div><small>Остаток A</small><b>${money(r.rem.A)}</b></div><div><small>Остаток B</small><b>${money(r.rem.B)}</b></div></div><div class="priority-line"><span>A ${money(r.pay.A)}</span><span>B ${money(r.pay.B)}</span><span>C ${money(r.pay.C)}</span><span>D ${money(r.pay.D)}</span></div><div class="field" style="margin-top:10px"><label>Комментарий</label><textarea data-month="${r.iso}" data-key="note" placeholder="Например: премия, незапланированные траты">${esc(r.note)}</textarea></div></section>`;}
function plan(){const sum=C.computePlan(state); view.innerHTML=`<div class="toolbar"><button class="btn primary" data-action="recalc">Пересчитать</button><button class="btn" data-action="add-months">+ 12 месяцев</button></div><section class="help-box">Поля можно менять без потери клавиатуры. Пересчет экрана происходит по кнопке или при переходе между вкладками.</section>${sum.rows.map(monthCard).join('')}`;}
function budget(){const sum=C.computePlan(state); view.innerHTML=`<section class="card"><h3>Бюджет</h3><p>Можно менять строки и добавлять новые. Новые данные сразу участвуют в расчете.</p></section><section class="card"><h3>Добавить строку</h3><div class="add-budget"><div class="field"><label>Приоритет</label><select id="newPriority"><option>A</option><option>B</option><option>C</option><option>D</option></select></div><div class="field"><label>Название</label><input id="newName" placeholder="Например: аккумулятор"></div><div class="field"><label>Сумма</label><input id="newAmount" type="number" min="0" step="100" placeholder="0"></div></div><div class="toolbar"><button class="btn primary" data-action="add-budget">Добавить</button></div></section>${state.budget.map((it,i)=>`<section class="card budget-row"><span class="badge ${it.priority}">${it.priority}</span><div class="budget-name"><input value="${esc(it.name)}" data-budget-name="${i}"></div><input class="amount-input" type="number" min="0" step="100" value="${Math.round(C.toNumber(it.amount))}" data-budget-amount="${i}"><button class="btn danger delete-btn" data-delete-budget="${i}">×</button></section>`).join('')}<section class="card"><h3>Итого с буфером</h3><div class="money-grid"><div><small>A</small><b>${money(sum.totals.target.A)}</b></div><div><small>B</small><b>${money(sum.totals.target.B)}</b></div><div><small>C</small><b>${money(sum.totals.target.C)}</b></div></div></section>`;}
function settings(){const s=state.settings; const info=s.priorities; view.innerHTML=`<section class="card"><h3>Вводные</h3><p>Названия приоритетов можно менять. Логика очереди останется A → B → C → D.</p></section><section class="card"><h3>Названия приоритетов</h3>${['A','B','C','D'].map(p=>`<div class="field"><label>${p}: название</label><input value="${esc(info[p].title)}" data-priority-title="${p}"></div><div class="field"><label>${p}: пояснение</label><textarea data-priority-desc="${p}">${esc(info[p].description)}</textarea></div>`).join('')}</section><section class="card settings-grid">${settingFields().map(([k,l,t,step])=>`<div class="field"><label>${l}</label><input type="${t}" step="${step||1}" value="${esc(s[k])}" data-setting="${k}"></div>`).join('')}</section>`;}
function settingFields(){return [['startDate','Дата старта','date'],['deadlineA','Дедлайн A','date'],['deadlineB','Дедлайн B','date'],['deadlineC','Дедлайн C','date'],['defaultIncome','Доход по умолчанию','number'],['defaultExpenses','Расходы без комнаты','number'],['maxRoom','Комната максимум','number'],['defaultRoom','Комната по умолчанию','number'],['startCash','Стартовый остаток','number'],['startRoom','Комната уже накоплено','number'],['reserve','Резерв','number'],['bufferAB','Буфер A/B','number','0.01'],['bufferC','Буфер C','number','0.01'],['bufferD','Буфер D','number','0.01'],['months','Месяцев в плане','number']];}
function dataView(){view.innerHTML=`<section class="card"><h3>Экспорт и импорт</h3><p>У каждого пользователя свои данные на своем телефоне. Для резервной копии скачивай JSON.</p><div class="toolbar"><button class="btn primary" data-action="export-json">Скачать JSON</button><label class="btn">Импорт JSON<input type="file" hidden accept="application/json" data-action="import-json"></label><button class="btn" data-action="export-csv">Скачать CSV</button><button class="btn danger" data-action="reset">Сбросить</button></div></section><section class="card"><div class="data-box">${esc(JSON.stringify(C.ensureState(state),null,2))}</div></section>`;}
function download(name,content,type){const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(){const s=C.computePlan(state); const head=['month','income','expenses','room','to_priority','goes_to','A','B','C','D','left_A','left_B','left_C','left_D','room_total','status']; const rows=s.rows.map(r=>[r.label,r.income,r.expenses,r.roomFact,r.toPriority,r.goesTo,r.pay.A,r.pay.B,r.pay.C,r.pay.D,r.rem.A,r.rem.B,r.rem.C,r.rem.D,r.roomTotal,r.status]); return [head,...rows].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');}
document.querySelector('.bottom-nav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]'); if(!b)return; activeTab=b.dataset.tab; render();});
view.addEventListener('input',e=>{const el=e.target;if(el.dataset.month){const iso=el.dataset.month,key=el.dataset.key;state.months[iso]=state.months[iso]||{};state.months[iso][key]=key==='note'?el.value:C.toNumber(el.value);saveSoon();return;} if(el.dataset.setting){state.settings[el.dataset.setting]=el.type==='date'?el.value:C.toNumber(el.value);saveSoon();return;} if(el.dataset.priorityTitle){state.settings.priorities[el.dataset.priorityTitle].title=el.value;saveSoon();return;} if(el.dataset.priorityDesc){state.settings.priorities[el.dataset.priorityDesc].description=el.value;saveSoon();return;} if(el.dataset.budgetAmount){state.budget[Number(el.dataset.budgetAmount)].amount=C.toNumber(el.value);saveSoon();return;} if(el.dataset.budgetName){state.budget[Number(el.dataset.budgetName)].name=el.value;saveSoon();return;}});
view.addEventListener('change',e=>{if(e.target.matches('input,textarea,select')){saveNow();}});
view.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='recalc'){saveNow();render();} if(action==='add-months'){state.settings.months=C.toNumber(state.settings.months,48)+12;saveNow();render();} if(action==='add-budget'){const p=document.getElementById('newPriority').value,n=document.getElementById('newName').value.trim(),a=C.toNumber(document.getElementById('newAmount').value); if(!n){alert('Введи название');return;} state.budget.push({priority:p,name:n,amount:a});saveNow();render();} if(action==='export-json')download('prioritycash-data.json',JSON.stringify(C.ensureState(state),null,2),'application/json'); if(action==='export-csv')download('prioritycash-months.csv',csv(),'text/csv;charset=utf-8'); if(action==='reset'&&confirm('Сбросить данные только на этом устройстве?')){state=C.clone(C.DEFAULT_STATE);saveNow();render();} const del=e.target.closest('[data-delete-budget]'); if(del&&confirm('Удалить строку бюджета?')){state.budget.splice(Number(del.dataset.deleteBudget),1);saveNow();render();}});
view.addEventListener('change',e=>{if(e.target.dataset.action==='import-json'){const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{state=C.ensureState(JSON.parse(r.result));saveNow();render();alert('Импорт готов');}catch(_){alert('Файл не похож на JSON приложения');}}; r.readAsText(f);}});

const APP_VERSION='2.1.0';
function setupAutoUpdate(){
  if(!('serviceWorker' in navigator) || location.protocol==='file:') return;
  let refreshing=false;
  navigator.serviceWorker.addEventListener('controllerchange',()=>{
    if(refreshing) return;
    refreshing=true;
    window.location.reload();
  });
  window.addEventListener('load',()=>{
    navigator.serviceWorker.register('sw.js').then(reg=>{
      function activateWaitingWorker(){
        if(reg.waiting) reg.waiting.postMessage({type:'SKIP_WAITING'});
      }
      activateWaitingWorker();
      reg.addEventListener('updatefound',()=>{
        const worker=reg.installing;
        if(!worker) return;
        worker.addEventListener('statechange',()=>{
          if(worker.state==='installed' && navigator.serviceWorker.controller){
            worker.postMessage({type:'SKIP_WAITING'});
          }
        });
      });
      setInterval(()=>reg.update().catch(()=>{}), 30*60*1000);
    }).catch(()=>{});
  });
}
setupAutoUpdate();
render();
})();
